#********************************************************************************
# The source code contained or described herein and all documents related to 
# the source code ("Material") are owned by Intel Corporation. Title to the 
# Material remains with Intel Corporation.
#
# No license under any patent, copyright, trade secret or other intellectual
# property right is granted to or conferred upon you by disclosure or delivery of
# the Materials, either expressly, by implication, inducement, estoppel or otherwise.
#*********************************************************************************

ARG EII_VERSION
ARG EII_UID
FROM uwc_test_common:$EII_VERSION as uwc_test_common
LABEL description="Modbus TCP Master Unit Testing container"

# Build MQTT-Bridge application
FROM ia_common:$EII_VERSION as mqtt-bridge
WORKDIR /

COPY MQTT-Bridge /MQTT-Bridge/. 
COPY --from=uwc_test_common /usr/lib/libpaho* /MQTT-Bridge/lib/
COPY --from=uwc_test_common /usr/paho-cpp/lib/lib* /MQTT-Bridge/lib/
COPY --from=uwc_test_common /usr/paho-cpp/include/mqtt /usr/local/include/mqtt
COPY --from=uwc_test_common /usr/include/MQTT* /MQTT-Bridge/include/
COPY --from=uwc_test_common /EII/log4cpp/build/include/log4cpp /MQTT-Bridge/include/log4cpp
COPY --from=uwc_test_common /EII/log4cpp/build/lib/* /MQTT-Bridge/lib/
COPY --from=uwc_test_common /usr/ssl/lib/* /usr/local/lib/
COPY --from=uwc_test_common /usr/ssl/include/* /usr/local/include/
COPY --from=uwc_test_common /EII/googletest-release-1.8.0/googletest/include/gtest /usr/local/include/gtest
COPY --from=uwc_test_common /EII/googletest-release-1.8.0/build/googlemock/gtest/libg* /usr/local/lib/
COPY --from=uwc_test_common /usr/yaml/include/yaml-cpp /usr/local/include/yaml-cpp
COPY --from=uwc_test_common /usr/yaml/lib/* /usr/local/lib/
COPY --from=uwc_test_common /uwc_util/Release/libuwc-common.so /MQTT-Bridge/lib/
COPY --from=uwc_test_common /uwc_util/include/* /MQTT-Bridge/include/

RUN cd /MQTT-Bridge/Build.test \
    &&	export LD_LIBRARY_PATH='/MQTT-Bridge/lib:/usr/local/lib' \
    &&  export INCLUDE_DIR='/bin' \
    &&	make clean all -s

RUN pip install gcovr

WORKDIR /MQTT-Bridge/Build.test
RUN chmod +x generateReport.sh
CMD ["./generateReport.sh"]
