# Copyright (c) 2021 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

ARG EII_VERSION
ARG EII_UID
FROM uwc_test_common:$EII_VERSION as uwc_test_common
FROM ia_eiibase:$EII_VERSION as eiibase
LABEL description="uwc-util library Unit Testing container"

# Build tahu library
FROM eiibase as build-tahu
RUN apt-get update && apt-get install -y libmosquitto-dev \
    &&  git clone --branch develop https://github.com/eclipse/tahu \
    && cd tahu \ 
    && git checkout 9bf91b69f5e9214e7ec765f2ad20acc7bc41236d \
    &&  cd client_libraries/c \
    && sed -i 's/#define SPARKPLUG_DEBUG 1/\/\/#define SPARKPLUG_DEBUG 0/g' include/tahu.h \
    &&	make -s

# Build uwc-util application
FROM ia_common:$EII_VERSION as uwc-util
WORKDIR /

RUN mkdir -p reports/uwc-util

# Create utils directory inside include

# copy required dependencies
COPY uwc_util /uwc_util/. 

COPY --from=uwc_test_common /usr/yaml/include/yaml-cpp /usr/local/include/yaml-cpp
COPY --from=uwc_test_common /usr/yaml/lib* /usr/local/lib/
COPY --from=uwc_test_common /usr/paho-cpp/lib/lib* /uwc_util/lib/
COPY --from=uwc_test_common /usr/lib/libpaho* /uwc_util/lib/
COPY --from=uwc_test_common /usr/paho-cpp/include/mqtt /usr/local/include/mqtt
COPY --from=uwc_test_common /usr/include/MQTT* /uwc_util/include/
COPY --from=uwc_test_common /EII/log4cpp/build/include/log4cpp /uwc_util/include/log4cpp
COPY --from=uwc_test_common /EII/log4cpp/build/lib/* /uwc_util/lib/
COPY --from=uwc_test_common /EII/googletest-release-1.8.0/googletest/include/gtest /usr/local/include/gtest
COPY --from=uwc_test_common /EII/googletest-release-1.8.0/build/googlemock/gtest/libg* /usr/local/lib/
COPY --from=uwc_test_common /usr/ssl/lib/* /usr/local/lib/
COPY --from=uwc_test_common /usr/ssl/include/* /usr/local/include/
COPY --from=build-tahu /tahu/client_libraries/c/lib/libtahu.so /uwc_util/lib/
COPY --from=build-tahu /tahu/client_libraries/c/include/* /uwc_util/include/tahu/
COPY --from=uwc_test_common $CMAKE_INSTALL_PREFIX/include /usr/local/include
COPY --from=uwc_test_common $CMAKE_INSTALL_PREFIX/lib /usr/local/lib

# compile uwc-util sources for 
RUN cd /uwc_util/Build.test \
    &&	export LD_LIBRARY_PATH='/uwc_util/lib' \
	#:/bin/yaml-cpp/lib' \
    #&&  export INCLUDE_DIR='/bin' \
    &&	make clean all -s

RUN pip install gcovr

WORKDIR /uwc_util/Build.test
RUN chmod +x generateReport.sh
CMD ["./generateReport.sh"]
