#********************************************************************************
# The source code contained or described herein and all documents related to 
# the source code ("Material") are owned by Intel Corporation. Title to the 
# Material remains with Intel Corporation.
#
# No license under any patent, copyright, trade secret or other intellectual
# property right is granted to or conferred upon you by disclosure or delivery of
# the Materials, either expressly, by implication, inducement, estoppel or otherwise.
#*********************************************************************************

ARG EII_VERSION
ARG EII_UID
FROM uwc_test_common:$EII_VERSION as uwc_test_common
FROM ia_eiibase:$EII_VERSION as eiibase
LABEL description="SPARKPLUG BRIDGE Unit Testing container"

# Build tahu library
FROM eiibase as build-tahu
RUN apt-get update && apt-get install -y libmosquitto-dev \
    &&  git clone --branch develop https://github.com/eclipse/tahu \
    && cd tahu \ 
    && git checkout 9bf91b69f5e9214e7ec765f2ad20acc7bc41236d \
    &&  cd client_libraries/c \
    && sed -i 's/#define SPARKPLUG_DEBUG 1/\/\/#define SPARKPLUG_DEBUG 0/g' include/tahu.h \
    &&	make -s

# Build Sparkplug-BRIDGE application
FROM ia_common:$EII_VERSION as sparkplug-bridge
WORKDIR /

RUN mkdir -p reports/sparkplug-bridge

# copy required dependencies
COPY SPARKPLUG-BRIDGE /SPARKPLUG-BRIDGE/. 

COPY --from=uwc_test_common /usr/yaml/include/yaml-cpp /usr/local/include/yaml-cpp
COPY --from=uwc_test_common /usr/yaml/lib* /usr/local/lib/
COPY --from=uwc_test_common /usr/paho-cpp/lib/lib* /SPARKPLUG-BRIDGE/lib/
COPY --from=uwc_test_common /usr/lib/libpaho* /SPARKPLUG-BRIDGE/lib/
COPY --from=uwc_test_common /usr/paho-cpp/include/mqtt /usr/local/include/mqtt
COPY --from=uwc_test_common /usr/include/MQTT* /SPARKPLUG-BRIDGE/include/
COPY --from=uwc_test_common /EII/log4cpp/build/include/log4cpp /SPARKPLUG-BRIDGE/include/log4cpp
COPY --from=uwc_test_common /EII/log4cpp/build/lib/* /SPARKPLUG-BRIDGE/lib/
COPY --from=uwc_test_common /EII/googletest-release-1.8.0/googletest/include/gtest /usr/local/include/gtest
COPY --from=uwc_test_common /EII/googletest-release-1.8.0/build/googlemock/gtest/libg* /usr/local/lib/
COPY --from=build-tahu /EII/tahu/client_libraries/c/lib/libtahu.so /SPARKPLUG-BRIDGE/lib/
COPY --from=build-tahu /EII/tahu/client_libraries/c/include/* /SPARKPLUG-BRIDGE/include/tahu/
COPY --from=uwc_test_common /uwc_util/Release/libuwc-common.so /SPARKPLUG-BRIDGE/lib/
COPY --from=uwc_test_common /uwc_util/include/* /SPARKPLUG-BRIDGE/include/

RUN cd /SPARKPLUG-BRIDGE/Build.test \
    &&	export LD_LIBRARY_PATH='/SPARKPLUG-BRIDGE/lib:/usr/local/lib' \
    &&  export INCLUDE_DIR='/bin' \
    &&	make clean all -s

RUN pip install gcovr

WORKDIR /SPARKPLUG-BRIDGE/Build.test
RUN chmod +x generateReport.sh
CMD ["./generateReport.sh"]
