version: '3.6'

services:

  ia_python_publisher:
    depends_on:
      - ia_eiibase
    build:
      context: $PWD/../uwc/Sample_Publisher
      dockerfile: $PWD/../uwc/Sample_Publisher/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        EII_UID: ${EII_UID}
        EII_USER_NAME: ${EII_USER_NAME}
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
        CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
        # set CMAKE_BUILD_TYPE value to "Debug" to generate debug symbols
        CMAKE_BUILD_TYPE: "Release"
    image: ${DOCKER_REGISTRY}ia_python_publisher:${EII_VERSION}
    container_name: ia_python_publisher
    hostname: ia_python_publisher
    restart: unless-stopped
    read_only: true
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    environment:
      AppName: "PythonPublisher"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      CertType: "zmq"
      # ZMQ_RECV_HWM: "1000"
    networks:
      - eii
    ports:
      - 65020:65020
      - 65117:65117
    volumes:
      - "vol_eii_socket:${SOCKET_DIR}"
    secrets:
      - ca_etcd
      - etcd_PythonPublisher_cert
      - etcd_PythonPublisher_key

secrets:
  etcd_PythonPublisher_cert:
    file: provision/Certificates/PythonPublisher/PythonPublisher_client_certificate.pem
  etcd_PythonPublisher_key:
    file: provision/Certificates/PythonPublisher/PythonPublisher_client_key.pem
