#********************************************************************************
# The source code contained or described herein and all documents related to 
# the source code ("Material") are owned by Intel Corporation. Title to the 
# Material remains with Intel Corporation.
#
# No license under any patent, copyright, trade secret or other intellectual
# property right is granted to or conferred upon you by disclosure or delivery of
# the Materials, either expressly, by implication, inducement, estoppel or otherwise.
#*********************************************************************************

ARG EIS_VERSION
ARG EIS_UID
FROM uwc_test_common:$EIS_VERSION as uwc_test_common
LABEL description="Scada-RTU Unit Testing container"

# Build Scada-RTU application
FROM ia_common:$EIS_VERSION as scada-rtu
WORKDIR /

RUN mkdir -p reports/scada-rtu

# copy required dependencies
COPY SCADA-RTU-APP /SCADA-RTU-APP/. 

COPY --from=uwc_test_common /usr/yaml/include/yaml-cpp /usr/local/include/yaml-cpp
COPY --from=uwc_test_common /usr/yaml/lib* /usr/local/lib/
COPY --from=uwc_test_common /usr/paho-cpp/lib/lib* /SCADA-RTU-APP/lib/
COPY --from=uwc_test_common /usr/lib/libpaho* /SCADA-RTU-APP/lib/
COPY --from=uwc_test_common /usr/paho-cpp/include/mqtt /usr/local/include/mqtt
COPY --from=uwc_test_common /usr/include/MQTT* /SCADA-RTU-APP/include/
COPY --from=uwc_test_common /EIS/log4cpp/build/include/log4cpp /SCADA-RTU-APP/include/log4cpp
COPY --from=uwc_test_common /EIS/log4cpp/build/lib/* /SCADA-RTU-APP/lib/
COPY --from=uwc_test_common /EIS/googletest-release-1.8.0/googletest/include/gtest /usr/local/include/gtest
COPY --from=uwc_test_common /EIS/googletest-release-1.8.0/build/googlemock/gtest/libg* /usr/local/lib/
COPY --from=uwc_test_common /EIS/tahu/client_libraries/c/lib/libtahu.so /SCADA-RTU-APP/lib/
COPY --from=uwc_test_common /EIS/tahu/client_libraries/c/include/* /SCADA-RTU-APP/include/tahu/

RUN cd /SCADA-RTU-APP/Build.test \
    &&	export LD_LIBRARY_PATH='/SCADA-RTU-APP/lib:/usr/local/lib' \
    &&  export INCLUDE_DIR='/bin' \
    &&	make clean all -s

RUN pip install gcovr

WORKDIR /SCADA-RTU-APP/Build.test
RUN chmod +x generateReport.sh
CMD ["./generateReport.sh"]
