diff --git 1/Dockerfile.eisbase 2/Dockerfile.eisbase
index fd124823..1e49d6ee 100644
--- 1/Dockerfile.eisbase
+++ 2/Dockerfile.eisbase
@@ -51,7 +51,11 @@ RUN git clone https://github.com/intel/safestringlib.git && \
 ENV CGO_CFLAGS "$CGO_FLAGS -O2 -D_FORTIFY_SOURCE=2 -Werror=format-security -fstack-protector-strong -fPIC"
 ENV CGO_LDFLAGS "$CGO_LDFLAGS -z noexecstack -z relro -z now"
 
-RUN go get go.etcd.io/etcd/client
+ENV ETCD_GO_PATH ${GOPATH}/src/go.etcd.io/etcd
+RUN mkdir -p ${ETCD_GO_PATH} && \
+    git clone https://github.com/etcd-io/etcd ${ETCD_GO_PATH} && \
+    cd ${ETCD_GO_PATH} && \
+    git checkout -b known_version 0c787e26bcd102c3bb14050ac893b07ba9ea029f
 
 ENV PY_WORK_DIR /EIS
 WORKDIR ${PY_WORK_DIR}
