#********************************************************************************
# The source code contained or described herein and all documents related to 
# the source code ("Material") are owned by Intel Corporation. Title to the 
# Material remains with Intel Corporation.
#
# No license under any patent, copyright, trade secret or other intellectual
# property right is granted to or conferred upon you by disclosure or delivery of
# the Materials, either expressly, by implication, inducement, estoppel or otherwise.
#*********************************************************************************

ARG EIS_VERSION
ARG EIS_UID
FROM uwc_test_common:$EIS_VERSION as uwc_test_common
LABEL description="KPI Tactic Unit Testing container"

# Build KPI Tactic application
FROM ia_common:$EIS_VERSION as kpitactic
WORKDIR /

RUN mkdir -p reports/kpi-tactics

# copy required dependencies
COPY KPIApp /KPIApp/. 
COPY --from=uwc_test_common /usr/yaml/include/yaml-cpp /usr/local/include/yaml-cpp
COPY --from=uwc_test_common /usr/yaml/lib/* /usr/local/lib/
COPY --from=uwc_test_common /usr/paho-cpp/lib/lib* /KPIApp/lib/
COPY --from=uwc_test_common /usr/lib/libpaho* /KPIApp/lib/
COPY --from=uwc_test_common /usr/ssl/lib/* /usr/local/lib/
COPY --from=uwc_test_common /usr/ssl/include/* /usr/local/include/
COPY --from=uwc_test_common /usr/paho-cpp/include/mqtt /usr/local/include/mqtt
COPY --from=uwc_test_common /usr/include/MQTT* /KPIApp/include/
COPY --from=uwc_test_common /EIS/log4cpp/build/include/log4cpp /KPIApp/include/log4cpp
COPY --from=uwc_test_common /EIS/log4cpp/build/lib/* /KPIApp/lib/
COPY --from=uwc_test_common /EIS/googletest-release-1.8.0/googletest/include/gtest /usr/local/include/gtest
COPY --from=uwc_test_common /EIS/googletest-release-1.8.0/build/googlemock/gtest/libg* /usr/local/lib/
COPY --from=uwc_test_common /uwc_util/Release/libuwc-common.so /KPIApp/lib/
COPY --from=uwc_test_common /uwc_util/include/* /KPIApp/include/


# build sources
RUN cd /KPIApp/Build.test \
    &&	export LD_LIBRARY_PATH='/KPIApp/lib:/usr/local/lib' \
    &&  export INCLUDE_DIR='/bin' \
    &&	make clean all -s

RUN pip install gcovr

WORKDIR /KPIApp/Build.test
RUN chmod +x generateReport.sh
CMD ["./generateReport.sh"]
