#********************************************************************************
# The source code contained or described herein and all documents related to 
# the source code ("Material") are owned by Intel Corporation. Title to the 
# Material remains with Intel Corporation.
#
# No license under any patent, copyright, trade secret or other intellectual
# property right is granted to or conferred upon you by disclosure or delivery of
# the Materials, either expressly, by implication, inducement, estoppel or otherwise.
#*********************************************************************************

ARG EII_VERSION
FROM uwc_test_common:$EII_VERSION as uwc_test_common
LABEL description="Modbus TCP Master Unit Testing container"

# Build Modbus Stack
FROM ia_common:$EII_VERSION as modbus-lib
WORKDIR /

COPY SoftMod_Stack /SoftMod_Stack/.
WORKDIR SoftMod_Stack
RUN cd Release \
    && make clean all -s

# Build Modbus application
FROM ia_common:$EII_VERSION as modbus-app

WORKDIR /
RUN mkdir -p reports/modbus-tcp-master
	
# Copy built library from images
COPY --from=uwc_test_common /usr/yaml /bin/yaml-cpp/.

COPY Modbus-App /Modbus-App/. 
COPY --from=modbus-lib /SoftMod_Stack/Release/libModbusMasterStack.so /Modbus-App/lib/
COPY --from=modbus-lib /SoftMod_Stack/Inc/API.h /Modbus-App/include/
COPY --from=uwc_test_common /EII/googletest-release-1.8.0/googletest/include/gtest /usr/local/include/gtest
COPY --from=uwc_test_common /EII/googletest-release-1.8.0/build/googlemock/gtest/libg* /usr/local/lib/
COPY --from=uwc_test_common /EII/log4cpp/build/include/log4cpp /Modbus-App/include/log4cpp
COPY --from=uwc_test_common /EII/log4cpp/build/lib/* /Modbus-App/lib/
COPY --from=uwc_test_common /usr/yaml/include/yaml-cpp /Modbus-App/include/
COPY --from=uwc_test_common /usr/yaml/lib* /Modbus-App/lib/
COPY --from=uwc_test_common /uwc_util/Release/libuwc-common.so /Modbus-App/lib/
COPY --from=uwc_test_common /uwc_util/include/* /Modbus-App/include/
COPY --from=uwc_test_common /usr/paho-cpp/lib/lib* /Modbus-App/lib/
COPY --from=uwc_test_common /usr/lib/libpaho* /Modbus-App/lib/
COPY --from=uwc_test_common /usr/paho-cpp/include/mqtt /usr/local/include/mqtt

RUN cp /Modbus-App/lib/* /usr/local/lib/
RUN cd /Modbus-App/Build.test \
    &&	export LD_LIBRARY_PATH='/Modbus-App/lib:/usr/local/lib\
    :/bin/yaml-cpp/lib' \
    &&  export INCLUDE_DIR='/bin' \
    &&	make clean all -s

RUN pip install gcovr

WORKDIR /Modbus-App/Build.test
RUN chmod +x generateReport.sh
CMD ["./generateReport.sh"]
