#********************************************************************************
# The source code contained or described herein and all documents related to 
# the source code ("Material") are owned by Intel Corporation. Title to the 
# Material remains with Intel Corporation.
#
# No license under any patent, copyright, trade secret or other intellectual
# property right is granted to or conferred upon you by disclosure or delivery of
# the Materials, either expressly, by implication, inducement, estoppel or otherwise.
#*********************************************************************************

ARG EIS_VERSION
FROM ia_eisbase:$EIS_VERSION as eisbase
LABEL description="Modbus TCP Master Unit Testing container"
ARG EIS_UID

FROM ia_common:$EIS_VERSION as common

# Build gtest lib
FROM eisbase as gtest-lib

RUN wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz \
				&& tar xzf release-1.8.0.tar.gz \
				&& cd googletest-release-1.8.0 \
				&& mkdir build \
				&& cd build \
				&& cmake .. \
				&& make -j \
				&& cp -r ../googletest/include /usr/local/include \
				&& cp -r ./googlemock/gtest/libgtest*.a /usr/local/lib/ \
				&& cp -r ./googlemock/libgmock*.a /usr/local/lib/ \
				&& pip install gcovr

# Build log4cpp Library
FROM eisbase as build-log4cpp

RUN wget https://sourceforge.net/projects/log4cpp/files/latest/download/log4cpp-1.1.3.tar.gz \
    && tar -zxvf log4cpp-1.1.3.tar.gz \
    && cd log4cpp && mkdir build \
    && ./configure --enable-static=no --prefix=$PWD/build \
    && make \
    && make install

# yaml build
FROM eisbase as build-yaml

RUN git clone --branch yaml-cpp-0.6.3 https://github.com/jbeder/yaml-cpp.git \
    && cd yaml-cpp \
    &&	mkdir build && cd build \
    &&	cmake -DYAML_BUILD_SHARED_LIBS=ON ../ \
    &&	make yaml-cpp \
    &&	mkdir -p /usr/yaml \
    &&  mkdir -p /usr/yaml/lib \
    &&  cp lib* /usr/yaml/lib \
    &&  cp -r ../include /usr/yaml \
    && cd ../../

# Build Modbus Stack
FROM eisbase as modbus-lib

WORKDIR /

COPY --from=common /usr/local/include/safe_* /usr/local/include/
COPY --from=common /usr/local/lib/libsafestring.so /usr/local/lib/

COPY SoftMod_Stack /SoftMod_Stack/.
WORKDIR SoftMod_Stack
RUN cd Release \
    && make clean all -s

# Build Modbus application
FROM eisbase as modbus-app

WORKDIR /
RUN mkdir -p reports/modbus-tcp-master

COPY --from=common /usr/local/include /usr/local/include
COPY --from=common /usr/local/lib /usr/local/lib
RUN apt-get update && apt-get install -y gcovr

# Copy built library from images
COPY --from=build-yaml /usr/yaml /bin/yaml-cpp/.

COPY Modbus-App /Modbus-App/. 
COPY --from=modbus-lib /SoftMod_Stack/Release/libModbusMasterStack.so /Modbus-App/lib/
COPY --from=modbus-lib /SoftMod_Stack/Inc/API.h /Modbus-App/include/
COPY --from=gtest-lib /EIS/googletest-release-1.8.0/googletest/include/gtest /usr/local/include/gtest
COPY --from=gtest-lib /EIS/googletest-release-1.8.0/build/googlemock/gtest/libg* /usr/local/lib/
COPY --from=build-log4cpp /EIS/log4cpp/build/include/log4cpp /Modbus-App/include/log4cpp
COPY --from=build-log4cpp /EIS/log4cpp/build/lib/* /Modbus-App/lib/
COPY --from=build-yaml /usr/yaml/include/yaml-cpp /Modbus-App/include/
COPY --from=build-yaml /usr/yaml/lib* /Modbus-App/lib/

RUN cp /Modbus-App/lib/* /usr/local/lib/
RUN cd /Modbus-App/Build.test \
    &&	export LD_LIBRARY_PATH='/Modbus-App/lib:/usr/local/lib\
    :/bin/yaml-cpp/lib' \
    &&  export INCLUDE_DIR='/bin' \
    &&	make clean all -s

WORKDIR /Modbus-App/Build.test
RUN chmod +x generateReport.sh
CMD ["./generateReport.sh"]
