#********************************************************************************
# The source code contained or described herein and all documents related to 
# the source code ("Material") are owned by Intel Corporation. Title to the 
# Material remains with Intel Corporation.
#
# No license under any patent, copyright, trade secret or other intellectual
# property right is granted to or conferred upon you by disclosure or delivery of
# the Materials, either expressly, by implication, inducement, estoppel or otherwise.
#*********************************************************************************

ARG EIS_VERSION
ARG EIS_UID
FROM uwc_test_common:$EIS_VERSION as uwc_test_common
LABEL description="Modbus RTU Master Unit Testing container"

# Build Modbus Stack
FROM ia_common:$EIS_VERSION as modbus-lib

WORKDIR /

COPY SoftMod_Stack /SoftMod_Stack/.
RUN sed -i 's/-DMODBUS_STACK_TCPIP_ENABLED//g' /SoftMod_Stack/Release/Src/subdir.mk 
WORKDIR SoftMod_Stack
RUN cd Release \
    && make clean all -s

# Build Modbus application
FROM ia_common:$EIS_VERSION as modbus-app

WORKDIR /
RUN mkdir -p reports/modbus-rtu-master

# Copy built library from images
COPY --from=uwc_test_common /usr/yaml /bin/yaml-cpp/.

COPY Modbus-App /Modbus-App/. 
COPY --from=modbus-lib /SoftMod_Stack/Release/libModbusMasterStack.so /Modbus-App/lib/
COPY --from=modbus-lib /SoftMod_Stack/Inc/API.h /Modbus-App/include/
COPY --from=uwc_test_common /EIS/googletest-release-1.8.0/googletest/include/gtest /usr/local/include/gtest
COPY --from=uwc_test_common /EIS/googletest-release-1.8.0/build/googlemock/gtest/libg* /usr/local/lib/
COPY --from=uwc_test_common /EIS/log4cpp/build/include/log4cpp /Modbus-App/include/log4cpp
COPY --from=uwc_test_common /EIS/log4cpp/build/lib/* /Modbus-App/lib/
COPY --from=uwc_test_common /usr/yaml/include/yaml-cpp /Modbus-App/include/
COPY --from=uwc_test_common /usr/yaml/lib* /Modbus-App/lib/

RUN cp /Modbus-App/lib/* /usr/local/lib/
RUN sed -i 's/-DMODBUS_STACK_TCPIP_ENABLED//g' /Modbus-App/Release/src/subdir.mk 
RUN sed -i 's/-DMODBUS_STACK_TCPIP_ENABLED//g' /Modbus-App/Release/src/utils/subdir.mk 
RUN cd /Modbus-App/Build.test \
    &&	export LD_LIBRARY_PATH='/Modbus-App/lib:/usr/local/lib\
    :/bin/yaml-cpp/lib' \
    &&  export INCLUDE_DIR='/bin' \
    &&	make clean all -s

RUN pip install gcovr

WORKDIR /Modbus-App/Build.test
RUN chmod +x generateReport_rtu.sh
CMD ["./generateReport_rtu.sh"]
