# Copyright (c) 2021 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

ARG EII_VERSION
ARG EII_UID
FROM uwc_test_common:$EII_VERSION as uwc_test_common
LABEL description="Modbus RTU Master Unit Testing container"

# Build Modbus Stack
FROM ia_common:$EII_VERSION as modbus-lib

WORKDIR /

COPY modconn /modconn/.
RUN sed -i 's/-DMODBUS_STACK_TCPIP_ENABLED//g' /modconn/Release/Src/subdir.mk 
WORKDIR modconn
RUN cd Release \
    && make clean all -s

# Build Modbus application
FROM ia_common:$EII_VERSION as modbus-app

WORKDIR /
RUN mkdir -p reports/modbus-rtu-master

# Copy built library from images
COPY --from=uwc_test_common /usr/yaml /bin/yaml-cpp/.

COPY Modbus-App /Modbus-App/. 
COPY --from=modbus-lib /modconn/Release/libModbusMasterStack.so /Modbus-App/lib/
COPY --from=modbus-lib /modconn/Inc/API.h /Modbus-App/include/
COPY --from=uwc_test_common /EII/googletest-release-1.8.0/googletest/include/gtest /usr/local/include/gtest
COPY --from=uwc_test_common /EII/googletest-release-1.8.0/build/googlemock/gtest/libg* /usr/local/lib/
COPY --from=uwc_test_common /EII/log4cpp/build/include/log4cpp /Modbus-App/include/log4cpp
COPY --from=uwc_test_common /EII/log4cpp/build/lib/* /Modbus-App/lib/
COPY --from=uwc_test_common /usr/yaml/include/yaml-cpp /Modbus-App/include/
COPY --from=uwc_test_common /usr/yaml/lib* /Modbus-App/lib/
COPY --from=uwc_test_common /uwc_util/Release/libuwc-common.so /Modbus-App/lib/
COPY --from=uwc_test_common /uwc_util/include/* /Modbus-App/include/
COPY --from=uwc_test_common /usr/paho-cpp/lib/lib* /Modbus-App/lib/
COPY --from=uwc_test_common /usr/lib/libpaho* /Modbus-App/lib/
COPY --from=uwc_test_common /usr/paho-cpp/include/mqtt /usr/local/include/mqtt

RUN cp /Modbus-App/lib/* /usr/local/lib/
RUN sed -i 's/-DMODBUS_STACK_TCPIP_ENABLED//g' /Modbus-App/Build.test/src/subdir.mk 
RUN sed -i 's/-DMODBUS_STACK_TCPIP_ENABLED//g' /Modbus-App/Build.test/Test/src/subdir.mk

COPY --from=uwc_test_common ${CMAKE_INSTALL_PREFIX}/include /usr/local/include
COPY --from=uwc_test_common ${CMAKE_INSTALL_PREFIX}/lib /usr/local/lib
COPY --from=uwc_test_common $CMAKE_INSTALL_PREFIX/lib /Modbus-App/lib
RUN cd /Modbus-App/Build.test \
    &&	export LD_LIBRARY_PATH='/Modbus-App/lib:/usr/local/lib\
    :/bin/yaml-cpp/lib' \
    &&  export INCLUDE_DIR='/bin' \
    &&	make clean all -s

RUN pip install gcovr

WORKDIR /Modbus-App/Build.test
RUN chmod +x generateReport_rtu.sh
CMD ["./generateReport_rtu.sh"]
